version: '3.8'

services:
  frontend:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "4000:4000"  
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}